use tiendapostres;
INSERT INTO sabor VALUES (1, "Chocolate");
INSERT INTO sabor VALUES (2, "Vainilla");
INSERT INTO sabor VALUES (3, "Limon");
INSERT INTO sabor VALUES (4, "Chocomenta");
INSERT INTO sabor VALUES (5, "Red Velvet");
INSERT INTO sabor VALUES (6, "Frutos rojos");
INSERT INTO sabor VALUES (7, "Frambuesas");
INSERT INTO sabor VALUES (8, "Fresas");
INSERT INTO sabor VALUES (9, "Queso");
INSERT INTO sabor VALUES (10, "Chocoamaretto");
INSERT INTO sabor VALUES (11, "Grosella");
INSERT INTO sabor VALUES (12, "Durazno");
INSERT INTO sabor VALUES (13, "Mango");
INSERT INTO sabor VALUES (14, "Coco");
INSERT INTO sabor VALUES (15, "Naranja");
INSERT INTO sabor VALUES (16, "Guayaba");
INSERT INTO sabor VALUES (17, "Manzana");
INSERT INTO sabor VALUES (18, "Mamey");
INSERT INTO sabor VALUES (19, "Cereza");
INSERT INTO sabor VALUES (20, "Galleta");
INSERT INTO sabor VALUES (21, "Cacahuate");
INSERT INTO sabor VALUES (22, "Queso con Zarzamora");
INSERT INTO sabor VALUES (23, "Chocolate con Vainilla");
INSERT INTO sabor VALUES (24, "Queso con Fresa");
INSERT INTO sabor VALUES (25, "Queso con Chabacano");
INSERT INTO sabor VALUES (26, "Almendra");
INSERT INTO sabor VALUES (27, "Cajeta");
INSERT INTO sabor VALUES (28, "Moka");
INSERT INTO sabor VALUES (29, "Queso con Chocolate");
INSERT INTO sabor VALUES (30, "Mil hojas");
INSERT INTO sabor VALUES (31, "Mil hojas de fresa");
INSERT INTO sabor VALUES (32, "Frutas");
INSERT INTO sabor VALUES (33, "Mantequilla");
INSERT INTO sabor VALUES (34, "Natural");
INSERT INTO sabor VALUES (35, "Nuez");
INSERT INTO sabor VALUES (36, "Avellana");
INSERT INTO sabor VALUES (37, "Capuchino");
INSERT INTO sabor VALUES (38, "Piña");
INSERT INTO sabor VALUES (39, "Chocolate y fresa");
INSERT INTO sabor VALUES (40, "Piñón");
INSERT INTO sabor VALUES (41, "Queso y Piña");
INSERT INTO sabor VALUES (42, "Macadamia");
INSERT INTO sabor VALUES (43, "Dulce de leche");
INSERT INTO sabor VALUES (44, "Oreo");
INSERT INTO sabor VALUES (45, "Stracciatella");
INSERT INTO sabor VALUES (46, "Yogurt con zarzamora");
INSERT INTO sabor VALUES (47, "Mango y yogurt de coco");
INSERT INTO sabor VALUES (48, "Zarzamora");
INSERT INTO sabor VALUES (49, "Nutella");
INSERT INTO sabor VALUES (50, "Cajeta con Tapioca");
SELECT * from sabor;
