INSERT INTO sabor VALUES (1, "Chocolate");
INSERT INTO sabor VALUES (2, "Vainilla");
INSERT INTO sabor VALUES (3, "Limon");
INSERT INTO sabor VALUES (4, "Chocomenta");
INSERT INTO sabor VALUES (5, "Red Velvet");
INSERT INTO sabor VALUES (6, "Frutos rojos");
INSERT INTO sabor VALUES (7, "Frambuesas");
INSERT INTO sabor VALUES (8, "Fresas");
INSERT INTO sabor VALUES (9, "Queso");
INSERT INTO sabor VALUES (10, "Z");
INSERT INTO sabor VALUES (11, "Grosella");
INSERT INTO sabor VALUES (12, "Durazno");
INSERT INTO sabor VALUES (13, "Mango");
INSERT INTO sabor VALUES (14, "Coco");
INSERT INTO sabor VALUES (15, "Naranja");
INSERT INTO sabor VALUES (16, "Guayaba");
INSERT INTO sabor VALUES (17, "Manzana");
INSERT INTO sabor VALUES (18, "Mamey");
INSERT INTO sabor VALUES (19, "Cereza");
INSERT INTO sabor VALUES (20, "Galleta");
INSERT INTO sabor VALUES (21, "Cacahuate");
SELECT * from sabor;
