--ESTRUCTURA PARA EL INSERT (idCliente, nombre, apellidoPaterno, apellidoMaterno, direccion, cp, email, password)
use tiendapostres;
INSERT INTO cliente VALUES(1,"Juan","Garcia","Medina","delegacion iztacalco","03900","juanga@hotmail.com","758s6");
INSERT INTO cliente VALUES(2,"Andrea","Lopez","Nieves","delegacion iztapalapa","03902","andreln@gmail.com","asde2356");
INSERT INTO cliente VALUES(3,"Julian","Sanchez","Marquez","delegacion iztacalco","03901","julians@gmail.com","orri4355");
INSERT INTO cliente VALUES(4,"Linda","Flores","Ruiz","delegacion iztacalco","03903","lindaf@gmail.com","09705843");
INSERT INTO cliente VALUES(5,"Karina","Mendez","Mendez","delegacion coyoacan","03940","karim@live.com","598sdt");
INSERT INTO cliente VALUES(6,"Laura","Garcia","Guarin","delegacion milpa alta","03930","laugg@hotmail.com","5vbc65fd");
INSERT INTO cliente VALUES(7,"Ordrep","Nieves","Sucre","delegacion coyoacan","03904","ordrepns@gmail.com","xclmkrt");
INSERT INTO cliente VALUES(8,"Jevet","Amieva","Soliz","delegacion benito juarez","03909","jevetas@hotmail.com","45676554");
INSERT INTO cliente VALUES(9,"Andrea","Ortiz","Ortiz","delegacion cuajimalpa","03910","andreaoo@live.com","5421565");
INSERT INTO cliente VALUES(10,"Rafael","Gomez","Castillo","delegacion alvaro obregon","03920","rafago@gmail.com","cnh5ty2");
INSERT INTO cliente VALUES(11,"Sebastian","Kurt","Perez","delegacion iztacalco","03900","sebaskurt@hotmail.com","potryrt45");
INSERT INTO cliente VALUES(12,"Maria","Martinez","Hernan","delegacion iztacalco","03900","mariahernan@gmail.com","75gfr2");
INSERT INTO cliente VALUES(13,"Luisa","Denis","Medina","delegacion benito juarez","03909","luisad@gmail.com","54jfdfgx");
INSERT INTO cliente VALUES(14,"Xavier","Garcia","Toledo","delegacion benito juarez","03909","drxavier@gmail.com","dgg6564");
INSERT INTO cliente VALUES(15,"Victoria","Flores","Nunez","delegacion coyoacan","03940","vickyf@live.com","52dsfsd");
INSERT INTO cliente VALUES(16,"Pedro","Zurita","Iglesia","delegacion coyoacan","03940","pedrozur@gmail.com","xcv5rtgf");
INSERT INTO cliente VALUES(17,"Karina","Castillo","Mendez","delegacion cuajimalpa","03980","karicasti@hotmail.com","sg65rgf");
INSERT INTO cliente VALUES(18,"Carmen","Lopez","Lopez","delegacion benito juarez","03990","carmenll@hotmail.com","hgj764");
INSERT INTO cliente VALUES(19,"Daniel","Hernandez","Sanchez","delegacion benito juarez","03990","danielhdz@gmail.com","fghs3");
INSERT INTO cliente VALUES(20,"Carlos","Fuentes","Perez","delegacion benito juarez","03990","carlosdp@hotmail.com","3435sf");

INSERT INTO cliente VALUES(21,"Alexander","Rodriguez","Cipres","delegacion iztacalco","03900","alexrc@hotmail.com","alex123");
INSERT INTO cliente VALUES(22,"Andrea","Guille","Torres","delegacion iztapalapa","03902","andregt@gmail.com","andrea1234");
INSERT INTO cliente VALUES(23,"Itzayana","Enrique","Ortiz","delegacion iztacalco","03901","itzaor@gmail.com","itz1234");
INSERT INTO cliente VALUES(24,"Lauren","Flores","Ruiz","delegacion iztacalco","03903","lauren@gmail.com","lau1234");
INSERT INTO cliente VALUES(25,"Karina","Figuero","Mendez","delegacion coyoacan","03940","kariff@live.com","kari12345");
INSERT INTO cliente VALUES(26,"Grecia","Gujardo","Guarin","delegacion milpa alta","03930","ggjuardo@hotmail.com","guaca123");
INSERT INTO cliente VALUES(27,"Jetze","Bustamante","Trujillo","delegacion coyoacan","03904","jetes@gmail.com","jetz123");
INSERT INTO cliente VALUES(28,"Jennifer","Amieva","Soliz","delegacion benito juarez","03909","jennier@hotmail.com","123jeni");
INSERT INTO cliente VALUES(29,"Andy","Ortiz","Carmona","delegacion cuajimalpa","03910","andreacco@live.com","andy0909");
INSERT INTO cliente VALUES(30,"Rafael","Santos","Cantu","delegacion alvaro obregon","03920","rafasc@gmail.com","raflor123");
INSERT INTO cliente VALUES(31,"Angel","Cobain","Perez","delegacion iztacalco","03900","angelcobain@hotmail.com","ac123456");
INSERT INTO cliente VALUES(32,"Mario","Martinez","Hernan","delegacion iztacalco","03900","mariohernan@gmail.com","mario123");
INSERT INTO cliente VALUES(33,"Luis","Ines","Medina","delegacion benito juarez","03909","luisines@gmail.com","luisic1");
INSERT INTO cliente VALUES(34,"Xavi","Fernandez","Toledo","delegacion benito juarez","03909","xavifer@gmail.com","xavi123");
INSERT INTO cliente VALUES(35,"Victor","Flores","Magon","delegacion coyoacan","03940","vickyfmago@live.com","elvicmago");
INSERT INTO cliente VALUES(36,"Pedro","Carmona","Aguilar","delegacion coyoacan","03940","pedroaguir@gmail.com","pedrin1");
INSERT INTO cliente VALUES(37,"Kami","Castillo","Cruz","delegacion cuajimalpa","03980","karicasticruz@hotmail.com","kastillo1");
INSERT INTO cliente VALUES(38,"Carmelo","Lopez","Lopez","delegacion benito juarez","03990","carmelo23@hotmail.com","carmelo123");
INSERT INTO cliente VALUES(39,"Daniela","Hernandez","Perez","delegacion benito juarez","03990","danielaperez1@gmail.com","danyp12");
INSERT INTO cliente VALUES(40,"Carlos","Velasco","Silva","delegacion benito juarez","03990","carlossillvav@hotmail.com","silvando1");

INSERT INTO cliente VALUES(41,"Marco","Salgado","Perez","delegacion iztacalco","03900","marcosalper@hotmail.com","salper12");
INSERT INTO cliente VALUES(42,"Daniel","Guarnero","Trejo","delegacion iztacalco","03900","guarneros@gmail.com","mustangt");
INSERT INTO cliente VALUES(43,"Osmar","Radilla","Flores","delegacion benito juarez","03909","osmarra@gmail.com","osmarsin");
INSERT INTO cliente VALUES(44,"Lex","Mendez","Infante","delegacion benito juarez","03909","lexmendez@gmail.com","infante1");
INSERT INTO cliente VALUES(45,"Juan","Chavez","Mazon","delegacion coyoacan","03940","jaunsincha@live.com","chabelito");
INSERT INTO cliente VALUES(46,"Samuel","Ortiz","Antunez","delegacion coyoacan","03940","elsamuel@gmail.com","chamiamu");
INSERT INTO cliente VALUES(47,"Cesia","Antunez","Ortiz","delegacion cuajimalpa","03980","lacesia@hotmail.com","laces22");
INSERT INTO cliente VALUES(48,"Ian","Ciprez","Trujillo","delegacion benito juarez","03990","elian@hotmail.com","superian");
INSERT INTO cliente VALUES(49,"Nissi","Santos","Enrique","delegacion benito juarez","03990","nissiquiera@gmail.com","nichi06");
INSERT INTO cliente VALUES(50,"Itzayana","Enrique","Ortiz","delegacion benito juarez","03990","itzablue@hotmail.com","miitza12");
SELECT * FROM cliente;